### ISSUE TITLE
No benchmarks / No estimates

### ISSUE THREAD

**Issue by NekoAlosama** [djdallmann/GamingPCSetup#9]
I would like to have something that shows me how optimized my PC could be by following the guide. FPS benchmarks, testimonials on how it feels to use as a whole, or more clarifications/explanations for why to do some steps.

One step I would like to have an explanation for on the step would be to disable Turbo Boost in the BIOS. Many people would like to have Turbo Boost frequencies, but they might be unwilling or unable to overclock their CPU. This can make people following the guide question why you should do such a change or just ignore the guide for the most part.

**Comment by djdallmann** [comment]
Thanks for submitting, my github isn't necessarily about getting the most FPS and overclocking. It's about stability, research, and guidelines with a lot of reputable technical references to help you decide what's best for you.

**Comment by NekoAlosama** [comment]
In that case, I would like you to make that explicit on the page. In the first line, people see the "optimizing your gaming PC, configuration and setup" and think of increasing their PC's performance and not necessarily making their PC last for a long time.

This takes me back to the 'disabling Turbo Boost' step. I can now understand that it's for stability purposes, but for people reading the guide it will be a turn-off.

Also. why do you want me to join the L&G discord?

**Comment by djdallmann** [comment]
Hopefully people aren't just reading the first line then skipping the bullet point summary and objectives. :D 

Optimizing really implies many things such as reducing and controlling variables which perhaps could improve performance, stability/reliability. The guide itself is just that, a guideline and ideally a good starting point for people.

For Turbo Boost what do you think about something like this?

**Turbo Boost**
- If isolating performance behavior issues, disable.
- If you'd like to use Turbo Boost frequencies I'd recommend using a static overclock to reduce minor overhead from dynamic frequency scaling, otherwise enable.

**Comment by NekoAlosama** [comment]
Looks good enough for me. I would want to have the first line to be a bit more descriptive in order for readers to know what exact definition of 'optimizing' we're using instead of just hoping they read more in-depth, but that's just my opinion; since no one else complained about it, you can leave that first sentence be.

Also. why do you want me to join the L&G discord?

**Comment by djdallmann** [comment]
A good discord on all things performance and latency.
